#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

if [[ ! -f ".worker.local.env" ]]; then
  echo "Missing .worker.local.env. Copy .worker.local.env.example and fill in your Cloudflare account, zone, worker names, and routes." >&2
  exit 1
fi

if [[ -f ".env" ]]; then
  # .env holds API credentials and stays untracked.
  source ./.env
fi

# .worker.local.env holds Cloudflare-specific values and stays untracked.
source ./.worker.local.env

env_source="${2:-staging}"
mode="${1:-staging}"

write_config() {
  local target_env="$1"
  local worker_name="$2"
  local route_pattern="$3"
  local tmp_config
  local repo_root
  repo_root="$(cd "$(dirname "$0")/.." && pwd)"
  # Use PID and RANDOM to ensure uniqueness
  tmp_config="/tmp/aiproxy-worker-$$.$(( RANDOM * RANDOM )).toml"

  cat > "$tmp_config" <<EOF
# Generated from scripts/worker.sh. Do not edit this file directly.
name = "$worker_name"
main = "$repo_root/src/worker/worker.js"
compatibility_date = "2026-06-11"
account_id = "$CF_ACCOUNT_ID"
workers_dev = true
preview_urls = false

[[routes]]
pattern = "$route_pattern"
zone_name = "$CF_ZONE_NAME"

[vars]
GEMINI_MODEL = "${CF_GEMINI_MODEL:-gemini-2.5-flash}"
GEMINI_API_BASE = "${CF_GEMINI_API_BASE:-https://generativelanguage.googleapis.com}"
GH_URL = "${CF_GH_URL:-https://models.inference.ai.azure.com/chat/completions}"
OPENROUTER_URL = "${CF_OPENROUTER_URL:-https://openrouter.ai/api/v1/chat/completions}"
DEEPSEEK_URL = "${CF_DEEPSEEK_URL:-https://api.deepseek.com/chat/completions}"
UPSTREAM_TIMEOUT_MS = "${CF_UPSTREAM_TIMEOUT_MS:-30000}"

[env.production]
name = "${CF_PROD_WORKER_NAME:-aiproxy}"
workers_dev = false
preview_urls = false

[[env.production.routes]]
pattern = "${CF_PROD_WORKER_ROUTE:-worker.example.com/*}"
zone_name = "$CF_ZONE_NAME"

[env.production.vars]
GEMINI_MODEL = "${CF_GEMINI_MODEL:-gemini-2.5-flash}"
GEMINI_API_BASE = "${CF_GEMINI_API_BASE:-https://generativelanguage.googleapis.com}"
GH_URL = "${CF_GH_URL:-https://models.inference.ai.azure.com/chat/completions}"
OPENROUTER_URL = "${CF_OPENROUTER_URL:-https://openrouter.ai/api/v1/chat/completions}"
DEEPSEEK_URL = "${CF_DEEPSEEK_URL:-https://api.deepseek.com/chat/completions}"
UPSTREAM_TIMEOUT_MS = "${CF_UPSTREAM_TIMEOUT_MS:-30000}"
EOF

  echo "$tmp_config"
}

check_wrangler_login() {
  if ! npx wrangler whoami >/dev/null 2>&1; then
    echo "Wrangler is not authenticated. Run 'npx wrangler login' on this machine first." >&2
    exit 1
  fi
}

deploy_env() {
  local target_env="$1"
  local worker_name="$2"
  local route_pattern="$3"
  local config_file

  check_wrangler_login

  if npx wrangler deployments list --name "$worker_name" --json >/dev/null 2>&1; then
    echo "Worker '$worker_name' already exists in Cloudflare; updating it now."
  else
    echo "Worker '$worker_name' does not exist yet; deploying will create it."
  fi

  config_file="$(write_config "$target_env" "$worker_name" "$route_pattern")"
  trap 'set +u; rm -f "$config_file" 2>/dev/null; set -u' EXIT

  if [[ "$target_env" == "production" ]]; then
    npx wrangler deploy -e production -c "$config_file"
  else
    npx wrangler deploy --env="" -c "$config_file"
  fi
}

run_dev() {
  local config_file
  check_wrangler_login

  config_file="$(write_config dev "${CF_DEV_WORKER_NAME:-aiproxy-dev}" "${CF_DEV_WORKER_ROUTE:-dev-worker.example.com/*}")"
  trap 'set +u; rm -f "$config_file" 2>/dev/null; set -u' EXIT

  echo "Starting local Worker emulation for '${CF_DEV_WORKER_NAME:-aiproxy-dev}'."
  echo "Required on this machine: 'npx wrangler login', '.env' for API credentials, and '.worker.local.env' for Cloudflare names/routes."
  npx wrangler dev --env="" -c "$config_file"
}

case "$mode" in
  dev)
    run_dev
    ;;
  deploy)
    if [[ "$env_source" == "production" ]]; then
      deploy_env production "${CF_PROD_WORKER_NAME:-aiproxy}" "${CF_PROD_WORKER_ROUTE:-worker.example.com/*}"
    else
      deploy_env staging "${CF_STAGING_WORKER_NAME:-aiproxy-staging}" "${CF_STAGING_WORKER_ROUTE:-staging-worker.example.com/*}"
    fi
    ;;
  *)
    echo "Usage: bash scripts/worker.sh [dev|deploy] [staging|production]" >&2
    exit 1
    ;;
esac